-- =====================================================================
-- 04 · Etiket görüntüleme adları (idempotent göç)
--
-- NEDEN: 25 Eylül 2026 persona testinde beş personanın beşi de etiketlerin
-- ASCII'ye katlandığını gördü ("Celik", "Cbam", "Cin", "Tcmb", "İso",
-- "Yesil Mutabakat"). Ölçüm: 402 etiketin yalnızca 71'inin adında Türkçe
-- harf vardı. İki kök neden:
--   1) ingestService.upsertTags ON DUPLICATE KEY'de `label = VALUES(label)`
--      yapıyordu; seed JSON'undaki etiketler düz string olduğu için ad
--      labelFromSlug() ile slug'dan türetiliyor ve 02_tags.sql'deki
--      küratörlü adı eziyordu (98 küratörlü etiketin haberde geçen 42'si;
--      aynı yolla 29'unun `kind`'ı da 'konu'ya döndü, bu dosya onu ELLEMEZ).
--      Upsert artık mevcut adı korur (bkz. ingestService.js).
--   2) Sözlükte olmayan 304 etiketin hiç doğru adı yoktu.
--
-- Bu dosya yalnızca `tags.label` yazar. `kind` ve `weight` ELLENMEZ:
-- canlıda satır varsa yalnızca adı düzelir; taze kurulumda (01→02→04 sonra
-- seed) satır yoksa varsayılan kind='konu', weight=40 ile eklenir. Bu,
-- seeder'ın aynı etiketi eklerken yazacağı değerin aynısıdır; seeder
-- sonra GREATEST ile ağırlığı yükseltebilir, adı artık değiştirmez.
-- Tekrar çalıştırmak güvenlidir (aynı değerleri yeniden yazar).
--
-- Yazım kuralları: kısaltmalar büyük harf (AB, ABD, TCMB, KOSGEB, TÜBİTAK,
-- TÜİK, OVP, PMI, CBAM, USITC); uluslararası standart adı ISO (noktasız),
-- İstanbul Sanayi Odası İSO; "X sanayii" belirtisiz ad tamlaması olarak
-- TDK yazımıyla. Anlamı belirsiz slug'lar kullanıldığı haberden çözüldü
-- (ör. melt-and-pour → haber 128 "eritme ve döküm", hes → haber 10
-- hidroelektrik santral, kore → haber 104/105 Güney Kore).
-- =====================================================================
SET NAMES utf8mb4;

-- (a) 02_tags.sql'deki küratörlü adların geri yüklenmesi (98 etiket).
--     Kaynak: 02_tags.sql, harfi harfine.
INSERT INTO tags (slug, label) VALUES
  ('mevzuat-degisikligi',           'Mevzuat Değişikliği'),
  ('resmi-gazete',                  'Resmî Gazete'),
  ('yonetmelik',                    'Yönetmelik'),
  ('teblig',                        'Tebliğ'),
  ('kanun',                         'Kanun'),
  ('cumhurbaskani-karari',          'Cumhurbaşkanı Kararı'),
  ('uyum-yukumlulugu',              'Uyum Yükümlülüğü'),
  ('tesvik',                        'Teşvik'),
  ('destek-programi',               'Destek Programı'),
  ('hibe',                          'Hibe'),
  ('cagri',                         'Proje Çağrısı'),
  ('yatirim-tesvik-belgesi',        'Yatırım Teşvik Belgesi'),
  ('ar-ge-tesviki',                 'Ar-Ge Teşviki'),
  ('kobi',                          'KOBİ'),
  ('vergi',                         'Vergi'),
  ('kdv-orani',                     'KDV Oranı'),
  ('kurumlar-vergisi',              'Kurumlar Vergisi'),
  ('faiz-karari',                   'Faiz Kararı'),
  ('kredi',                         'Kredi'),
  ('kur',                           'Döviz Kuru'),
  ('enflasyon',                     'Enflasyon'),
  ('ihracat',                       'İhracat'),
  ('ithalat',                       'İthalat'),
  ('gumruk',                        'Gümrük'),
  ('tarife',                        'Tarife'),
  ('anti-damping',                  'Anti-Damping'),
  ('korunma-onlemi',                'Korunma Önlemi'),
  ('ticaret-politikasi',            'Ticaret Politikası'),
  ('gumruk-birligi',                'Gümrük Birliği'),
  ('serbest-ticaret-anlasmasi',     'Serbest Ticaret Anlaşması'),
  ('cbam',                          'CBAM (Sınırda Karbon)'),
  ('yesil-mutabakat',               'Yeşil Mutabakat'),
  ('karbon-fiyatlamasi',            'Karbon Fiyatlaması'),
  ('emisyon-ticaret-sistemi',       'Emisyon Ticaret Sistemi'),
  ('surdurulebilirlik-raporlamasi', 'Sürdürülebilirlik Raporlaması'),
  ('csrd',                          'CSRD'),
  ('dongusel-ekonomi',              'Döngüsel Ekonomi'),
  ('enerji-maliyeti',               'Enerji Maliyeti'),
  ('dogalgaz',                      'Doğal Gaz'),
  ('elektrik-tarifesi',             'Elektrik Tarifesi'),
  ('petrol',                        'Petrol'),
  ('yenilenebilir-enerji',          'Yenilenebilir Enerji'),
  ('sanayi-uretimi',                'Sanayi Üretimi'),
  ('pmi',                           'PMI'),
  ('kapasite-kullanimi',            'Kapasite Kullanımı'),
  ('tedarik-zinciri',               'Tedarik Zinciri'),
  ('lojistik',                      'Lojistik'),
  ('navlun',                        'Navlun'),
  ('emtia-fiyatlari',               'Emtia Fiyatları'),
  ('asgari-ucret',                  'Asgari Ücret'),
  ('istihdam',                      'İstihdam'),
  ('sgk',                           'SGK'),
  ('is-sagligi-guvenligi',          'İş Sağlığı ve Güvenliği'),
  ('yapay-zeka',                    'Yapay Zekâ'),
  ('dijitallesme',                  'Dijitalleşme'),
  ('sanayi-40',                     'Sanayi 4.0'),
  ('siber-guvenlik',                'Siber Güvenlik'),
  ('yari-iletken',                  'Yarı İletken'),
  ('standart',                      'Standart'),
  ('patent',                        'Patent'),
  ('demir-celik',                   'Demir-Çelik'),
  ('otomotiv',                      'Otomotiv'),
  ('tekstil',                       'Tekstil'),
  ('kimya',                         'Kimya'),
  ('makine',                        'Makine'),
  ('gida',                          'Gıda'),
  ('insaat',                        'İnşaat'),
  ('elektronik',                    'Elektronik'),
  ('savunma-sanayi',                'Savunma Sanayi'),
  ('ilac',                          'İlaç'),
  ('cimento',                       'Çimento'),
  ('aluminyum',                     'Alüminyum'),
  ('iso',                           'İstanbul Sanayi Odası'),
  ('isov',                          'İSOV'),
  ('kosgeb',                        'KOSGEB'),
  ('tubitak',                       'TÜBİTAK'),
  ('tcmb',                          'TCMB'),
  ('tuik',                          'TÜİK'),
  ('ticaret-bakanligi',             'Ticaret Bakanlığı'),
  ('sanayi-bakanligi',              'Sanayi ve Teknoloji Bakanlığı'),
  ('tobb',                          'TOBB'),
  ('tim',                           'TİM'),
  ('eximbank',                      'Türk Eximbank'),
  ('ab-komisyonu',                  'Avrupa Komisyonu'),
  ('wto',                           'WTO'),
  ('imf',                           'IMF'),
  ('dunya-bankasi',                 'Dünya Bankası'),
  ('oecd',                          'OECD'),
  ('fed',                           'FED'),
  ('ecb',                           'ECB'),
  ('ustr',                          'USTR'),
  ('turkiye',                       'Türkiye'),
  ('avrupa-birligi',                'Avrupa Birliği'),
  ('abd',                           'ABD'),
  ('cin',                           'Çin'),
  ('almanya',                       'Almanya'),
  ('asya',                          'Asya'),
  ('korfez',                        'Körfez Ülkeleri')
AS new
ON DUPLICATE KEY UPDATE label = new.label;

-- (b) Sözlükte olmayan etiketlerin elle kontrol edilmiş adları (304 etiket).
INSERT INTO tags (slug, label) VALUES
  ('ab-celik-korunma',            'AB Çelik Korunma'),
  ('ab-destegi',                  'AB Desteği'),
  ('ab-fonlari',                  'AB Fonları'),
  ('ab-mevzuati',                 'AB Mevzuatı'),
  ('ab-turkiye',                  'AB-Türkiye'),
  ('abd-enflasyonu',              'ABD Enflasyonu'),
  ('adana',                       'Adana'),
  ('afcfta',                      'AfCFTA'),
  ('afrika-pazari',               'Afrika Pazarı'),
  ('akaryakit',                   'Akaryakıt'),
  ('altin-fiyati',                'Altın Fiyatı'),
  ('altyapi',                     'Altyapı'),
  ('ambalaj',                     'Ambalaj'),
  ('ar-ge',                       'Ar-Ge'),
  ('ardeb',                       'ARDEB'),
  ('arz-acigi',                   'Arz Açığı'),
  ('arz-daralmasi',               'Arz Daralması'),
  ('atik',                        'Atık'),
  ('avro-bolgesi',                'Avro Bölgesi'),
  ('avrupa-sanayisi',             'Avrupa Sanayisi'),
  ('bab-el-mendep',               'Babülmendep'),
  ('bae',                         'BAE'),
  ('bakir-fiyati',                'Bakır Fiyatı'),
  ('bankacilik',                  'Bankacılık'),
  ('basvuru',                     'Başvuru'),
  ('bddk',                        'BDDK'),
  ('belgelendirme',               'Belgelendirme'),
  ('bigg',                        'BiGG'),
  ('bildirim-yukumlulugu',        'Bildirim Yükümlülüğü'),
  ('bitkisel-uretim',             'Bitkisel Üretim'),
  ('borsa-istanbul',              'Borsa İstanbul'),
  ('brent',                       'Brent'),
  ('bsmv',                        'BSMV'),
  ('butce',                       'Bütçe'),
  ('buyume',                      'Büyüme'),
  ('cari-acik',                   'Cari Açık'),
  ('cari-denge',                  'Cari Denge'),
  ('cekirdek-enflasyon',          'Çekirdek Enflasyon'),
  ('celik',                       'Çelik'),
  ('cevre-mevzuati',              'Çevre Mevzuatı'),
  ('cin-ihracati',                'Çin İhracatı'),
  ('cin-rekabeti',                'Çin Rekabeti'),
  ('cop31',                       'COP31'),
  ('damga-vergisi',               'Damga Vergisi'),
  ('degerli-metaller',            'Değerli Metaller'),
  ('demiryolu',                   'Demiryolu'),
  ('depolama',                    'Depolama'),
  ('destekleme',                  'Destekleme'),
  ('dezenflasyon',                'Dezenflasyon'),
  ('dijital-donusum',             'Dijital Dönüşüm'),
  ('dijital-ortam',               'Dijital Ortam'),
  ('dis-ticaret',                 'Dış Ticaret'),
  ('dis-ticaret-acigi',           'Dış Ticaret Açığı'),
  ('dogal-gaz',                   'Doğal Gaz'),
  ('dolar-kuru',                  'Dolar Kuru'),
  ('drewry',                      'Drewry'),
  ('duyuru',                      'Duyuru'),
  ('e-ihracat',                   'E-İhracat'),
  ('e-ticaret',                   'E-Ticaret'),
  ('egitim',                      'Eğitim'),
  ('eic',                         'EIC'),
  ('ekonomik-gosterge',           'Ekonomik Gösterge'),
  ('elektrik-dagitim',            'Elektrik Dağıtım'),
  ('elektrikli-arac',             'Elektrikli Araç'),
  ('emtia',                       'Emtia'),
  ('endustri-bolgesi',            'Endüstri Bölgesi'),
  ('enerji',                      'Enerji'),
  ('enerji-enflasyonu',           'Enerji Enflasyonu'),
  ('enerji-iletim-hatti',         'Enerji İletim Hattı'),
  ('enerji-ithalati',             'Enerji İthalatı'),
  ('enerji-piyasasi',             'Enerji Piyasası'),
  ('epdk',                        'EPDK'),
  ('eskisehir',                   'Eskişehir'),
  ('etkinlik',                    'Etkinlik'),
  ('euro',                        'Euro'),
  ('euro-bolgesi',                'Euro Bölgesi'),
  ('faiz',                        'Faiz'),
  ('fikri-mulkiyet',              'Fikri Mülkiyet'),
  ('finansman',                   'Finansman'),
  ('finansman-maliyeti',          'Finansman Maliyeti'),
  ('fiyat-rekabeti',              'Fiyat Rekabeti'),
  ('fransa',                      'Fransa'),
  ('gelir-vergisi',               'Gelir Vergisi'),
  ('gemi-trafigi',                'Gemi Trafiği'),
  ('genc-issizlik',               'Genç İşsizlik'),
  ('geri-donusum',                'Geri Dönüşüm'),
  ('gida-sanayi',                 'Gıda Sanayii'),
  ('girdi-maliyeti',              'Girdi Maliyeti'),
  ('girisim-istatistikleri',      'Girişim İstatistikleri'),
  ('girisimcilik',                'Girişimcilik'),
  ('gtip',                        'GTİP'),
  ('gumruk-vergisi',              'Gümrük Vergisi'),
  ('guvenli-liman',               'Güvenli Liman'),
  ('halka-aciklik',               'Halka Açıklık'),
  ('hammadde',                    'Hammadde'),
  ('hammadde-arzi',               'Hammadde Arzı'),
  ('hammadde-maliyeti',           'Hammadde Maliyeti'),
  ('hayvancilik-destegi',         'Hayvancılık Desteği'),
  ('hes',                         'HES'),
  ('hindistan',                   'Hindistan'),
  ('hizmetler',                   'Hizmetler'),
  ('horizon-europe',              'Horizon Europe'),
  ('hormuz-bogazi',               'Hürmüz Boğazı'),
  ('hurda',                       'Hurda'),
  ('hurmuz-bogazi',               'Hürmüz Boğazı'),
  ('ic-talep',                    'İç Talep'),
  ('idari-para-cezasi',           'İdari Para Cezası'),
  ('iea',                         'IEA'),
  ('ihale',                       'İhale'),
  ('ihracat-destegi',             'İhracat Desteği'),
  ('ihracat-finansmani',          'İhracat Finansmanı'),
  ('ihracat-kontrolu',            'İhracat Kontrolü'),
  ('ihracat-kotasi',              'İhracat Kotası'),
  ('ihracat-maliyeti',            'İhracat Maliyeti'),
  ('ihracat-pazari',              'İhracat Pazarı'),
  ('ihracat-siparisi',            'İhracat Siparişi'),
  ('ihracat-vergisi',             'İhracat Vergisi'),
  ('iklim-degisikligi',           'İklim Değişikliği'),
  ('iklim-finansmani',            'İklim Finansmanı'),
  ('imalat-pmi',                  'İmalat PMI'),
  ('imalat-sanayi',               'İmalat Sanayii'),
  ('inovasyon',                   'İnovasyon'),
  ('insan-kaynaklari',            'İnsan Kaynakları'),
  ('insansiz-hava-araci',         'İnsansız Hava Aracı'),
  ('ipa',                         'IPA'),
  ('isgucu',                      'İşgücü'),
  ('isletme-sermayesi',           'İşletme Sermayesi'),
  ('iso-45001',                   'ISO 45001'),
  ('iso-45010',                   'ISO 45010'),
  ('iso-9001',                    'ISO 9001'),
  ('iso-pmi',                     'İSO PMI'),
  ('issizlik',                    'İşsizlik'),
  ('istanbul',                    'İstanbul'),
  ('istka',                       'İSTKA'),
  ('italya',                      'İtalya'),
  ('ithalat-bagimliligi',         'İthalat Bağımlılığı'),
  ('ithalat-yasagi',              'İthalat Yasağı'),
  ('izin-belgesi',                'İzin Belgesi'),
  ('izlenebilirlik',              'İzlenebilirlik'),
  ('japonya',                     'Japonya'),
  ('jeopolitik-risk',             'Jeopolitik Risk'),
  ('kalite-yonetimi',             'Kalite Yönetimi'),
  ('kalkinma-ajansi',             'Kalkınma Ajansı'),
  ('kamu-alimlari',               'Kamu Alımları'),
  ('kamu-maliyesi',               'Kamu Maliyesi'),
  ('kamu-yatirim-programi',       'Kamu Yatırım Programı'),
  ('kamulastirma',                'Kamulaştırma'),
  ('kanada',                      'Kanada'),
  ('kapasite-fazlasi',            'Kapasite Fazlası'),
  ('kapasite-gelistirme',         'Kapasite Geliştirme'),
  ('karbon',                      'Karbon'),
  ('karbon-piyasasi',             'Karbon Piyasası'),
  ('karsiliklilik',               'Karşılıklılık'),
  ('kayit-yukumlulugu',           'Kayıt Yükümlülüğü'),
  ('kgf',                         'KGF'),
  ('kizildeniz',                  'Kızıldeniz'),
  ('kkdik',                       'KKDİK'),
  ('kobi-finansmani',             'KOBİ Finansmanı'),
  ('konteyner',                   'Konteyner'),
  ('konteyner-navlunu',           'Konteyner Navlunu'),
  ('kore',                        'Kore'),
  ('korumacilik',                 'Korumacılık'),
  ('kredi-destegi',               'Kredi Desteği'),
  ('kredi-maliyeti',              'Kredi Maliyeti'),
  ('kritik-hammadde',             'Kritik Hammadde'),
  ('kur-riski',                   'Kur Riski'),
  ('kuresel-rekabetcilik',        'Küresel Rekabetçilik'),
  ('kuresel-talep',               'Küresel Talep'),
  ('kuyumculuk',                  'Kuyumculuk'),
  ('liman',                       'Liman'),
  ('lme',                         'LME'),
  ('lng',                         'LNG'),
  ('madencilik',                  'Madencilik'),
  ('makine-yatirimi',             'Makine Yatırımı'),
  ('makroekonomi',                'Makroekonomi'),
  ('mali-destek',                 'Mali Destek'),
  ('mali-disiplin',               'Mali Disiplin'),
  ('maliyet',                     'Maliyet'),
  ('maliyet-baskisi',             'Maliyet Baskısı'),
  ('malvarligi-dondurma',         'Malvarlığı Dondurma'),
  ('marka-tescili',               'Marka Tescili'),
  ('masak',                       'MASAK'),
  ('melt-and-pour',               'Eritme ve Döküm'),
  ('mense-kurali',                'Menşe Kuralı'),
  ('mensei-kurallari',            'Menşe Kuralları'),
  ('meslek-standardi',            'Meslek Standardı'),
  ('metal-esya',                  'Metal Eşya'),
  ('metal-sanayi',                'Metal Sanayii'),
  ('miknatis',                    'Mıknatıs'),
  ('misilleme',                   'Misilleme'),
  ('motorin',                     'Motorin'),
  ('mutaahhitlik',                'Müteahhitlik'),
  ('myk',                         'MYK'),
  ('nadir-toprak',                'Nadir Toprak'),
  ('nakit-yonetimi',              'Nakit Yönetimi'),
  ('nitelikli-isgucu',            'Nitelikli İşgücü'),
  ('odemeler-dengesi',            'Ödemeler Dengesi'),
  ('on-gerilmeli-celik-tel',      'Ön Gerilmeli Çelik Tel'),
  ('oncelikli-finansman',         'Öncelikli Finansman'),
  ('opec',                        'OPEC'),
  ('organize-sanayi-bolgesi',     'Organize Sanayi Bölgesi'),
  ('orta-vadeli-program',         'Orta Vadeli Program'),
  ('otomotiv-rekabeti',           'Otomotiv Rekabeti'),
  ('ovp',                         'OVP'),
  ('para-piyasasi-fonu',          'Para Piyasası Fonu'),
  ('para-politikasi',             'Para Politikası'),
  ('paris-anlasmasi',             'Paris Anlaşması'),
  ('parite',                      'Parite'),
  ('pboc',                        'PBoC'),
  ('perakende',                   'Perakende'),
  ('petrokimya',                  'Petrokimya'),
  ('petrokimya-hammaddesi',       'Petrokimya Hammaddesi'),
  ('petrol-fiyati',               'Petrol Fiyatı'),
  ('petrol-talebi',               'Petrol Talebi'),
  ('pil',                         'Pil'),
  ('politika-faizi',              'Politika Faizi'),
  ('prim-tesviki',                'Prim Teşviki'),
  ('proje-cagrisi',               'Proje Çağrısı'),
  ('proje-destegi',               'Proje Desteği'),
  ('rafineri-marji',              'Rafineri Marjı'),
  ('reeskont-kredisi',            'Reeskont Kredisi'),
  ('rekabet',                     'Rekabet'),
  ('rekabet-hukuku',              'Rekabet Hukuku'),
  ('rekabetcilik',                'Rekabetçilik'),
  ('repo',                        'Repo'),
  ('rezervler',                   'Rezervler'),
  ('sakarya',                     'Sakarya'),
  ('sanayi',                      'Sanayi'),
  ('sanayi-arsasi',               'Sanayi Arsası'),
  ('sanayi-politikasi',           'Sanayi Politikası'),
  ('sanayi-yatirimi',             'Sanayi Yatırımı'),
  ('section-232',                 'Section 232'),
  ('section-338',                 'Section 338'),
  ('senaryo-planlama',            'Senaryo Planlama'),
  ('serbest-bolge',               'Serbest Bölge'),
  ('serbest-ticaret',             'Serbest Ticaret'),
  ('sermaye-piyasasi',            'Sermaye Piyasası'),
  ('sermaye-yeterliligi',         'Sermaye Yeterliliği'),
  ('sertifikasyon',               'Sertifikasyon'),
  ('sigorta',                     'Sigorta'),
  ('sinai-mulkiyet',              'Sınai Mülkiyet'),
  ('siparis',                     'Sipariş'),
  ('siparis-ar-ge',               'Sipariş Ar-Ge'),
  ('son-basvuru',                 'Son Başvuru'),
  ('spk',                         'SPK'),
  ('stok-yonetimi',               'Stok Yönetimi'),
  ('stopaj',                      'Stopaj'),
  ('su-yonetimi',                 'Su Yönetimi'),
  ('sunset-review',               'Sunset Review'),
  ('surdurulebilirlik',           'Sürdürülebilirlik'),
  ('suudi-arabistan',             'Suudi Arabistan'),
  ('suveys',                      'Süveyş'),
  ('suveys-kanali',               'Süveyş Kanalı'),
  ('takas',                       'Takas'),
  ('takipteki-krediler',          'Takipteki Krediler'),
  ('tarimsal-destek',             'Tarımsal Destek'),
  ('tasarim',                     'Tasarım'),
  ('tasarruf-tedbirleri',         'Tasarruf Tedbirleri'),
  ('tayvan',                      'Tayvan'),
  ('tedarik-cesitlendirme',       'Tedarik Çeşitlendirme'),
  ('tedarik-sanayi',              'Tedarik Sanayii'),
  ('tedarikci-denetimi',          'Tedarikçi Denetimi'),
  ('teknoloji',                   'Teknoloji'),
  ('telafi-edici-vergi',          'Telafi Edici Vergi'),
  ('temiz-teknoloji',             'Temiz Teknoloji'),
  ('teydeb',                      'TEYDEB'),
  ('ticaret-fazlasi',             'Ticaret Fazlası'),
  ('ticaret-heyeti',              'Ticaret Heyeti'),
  ('ticaret-savasi',              'Ticaret Savaşı'),
  ('ticaret-savunmasi',           'Ticaret Savunması'),
  ('transpasifik',                'Transpasifik'),
  ('tse',                         'TSE'),
  ('ttf-fiyati',                  'TTF Fiyatı'),
  ('tufe',                        'TÜFE'),
  ('turizm',                      'Turizm'),
  ('turkiye-100',                 'Türkiye 100'),
  ('turkiye-mensei',              'Türkiye Menşei'),
  ('turkpatent',                  'TÜRKPATENT'),
  ('ucret-destegi',               'Ücret Desteği'),
  ('ucret-tarifesi',              'Ücret Tarifesi'),
  ('ufe',                         'ÜFE'),
  ('ufuk-avrupa',                 'Ufuk Avrupa'),
  ('universite-sanayi-isbirligi', 'Üniversite-Sanayi İş Birliği'),
  ('ur-ge',                       'UR-GE'),
  ('uretici-fiyatlari',           'Üretici Fiyatları'),
  ('uretim',                      'Üretim'),
  ('usitc',                       'USITC'),
  ('uyum',                        'Uyum'),
  ('uyusmazlik-cozumu',           'Uyuşmazlık Çözümü'),
  ('vergi-denetimi',              'Vergi Denetimi'),
  ('vergi-istisnasi',             'Vergi İstisnası'),
  ('vergi-orani',                 'Vergi Oranı'),
  ('vergi-usul-kanunu',           'Vergi Usul Kanunu'),
  ('veri-analizi',                'Veri Analizi'),
  ('veri-merkezi',                'Veri Merkezi'),
  ('verimlilik',                  'Verimlilik'),
  ('vietnam',                     'Vietnam'),
  ('volatilite',                  'Volatilite'),
  ('yaptirim',                    'Yaptırım'),
  ('yaratici-ekonomi',            'Yaratıcı Ekonomi'),
  ('yatirim',                     'Yatırım'),
  ('yatirim-tesvik',              'Yatırım Teşvik'),
  ('yeni-siparis',                'Yeni Sipariş'),
  ('yurtdisi-yatirim',            'Yurt Dışı Yatırım')
AS new
ON DUPLICATE KEY UPDATE label = new.label;
